"""initial schema

Revision ID: 1ca30a28e0e0
Revises: 
Create Date: 2026-04-07 19:10:41.307565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca30a28e0e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_tags_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_roadmap_tags_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role', native_enum=False), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_slug'), ['slug'], unique=True)

    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), server_default='article', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'parent_id', 'position', name='uq_node_sibling_position')
    )
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_nodes_roadmap_id'), ['roadmap_id'], unique=False)

    op.create_table('roadmap_tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['roadmap_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'tag_id', name='uq_roadmap_tag_link')
    )
    with op.batch_alter_table('roadmap_tag_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_tag_links_roadmap_id'), ['roadmap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_tag_links_tag_id'), ['tag_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('resource_type', sa.String(length=50), server_default='link', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_node_id'), ['node_id'], unique=False)

    op.create_table('user_node_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', name='progress_status', native_enum=False), server_default='not_started', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id', name='uq_user_node_progress')
    )
    with op.batch_alter_table('user_node_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_node_progress_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_node_progress_roadmap_id'), ['roadmap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_node_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_node_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_node_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_node_progress_roadmap_id'))
        batch_op.drop_index(batch_op.f('ix_user_node_progress_node_id'))

    op.drop_table('user_node_progress')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_node_id'))

    op.drop_table('resources')
    with op.batch_alter_table('roadmap_tag_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_tag_links_tag_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_tag_links_roadmap_id'))

    op.drop_table('roadmap_tag_links')
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_nodes_roadmap_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_nodes_parent_id'))

    op.drop_table('roadmap_nodes')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_slug'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_level'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_category'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_author_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roadmap_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_tags_slug'))
        batch_op.drop_index(batch_op.f('ix_roadmap_tags_name'))

    op.drop_table('roadmap_tags')
    # ### end Alembic commands ###
